### ISSUE TITLE
repoze.zodbconn.connector middleware not support streaming application

### ISSUE THREAD

**Issue by harobed** [repoze/repoze.zodbconn#1]
I've put in repoze.zodbconn.connector one application that return iterator.

Unfortunately repoze.zodbconn.connector middleware not support this application.

I've create a patch to support it : https://github.com/harobed/repoze.zodbconn/commit/d49213a5841de339f285af8e83baa55858df270e

What do you think about this patch ?

Regards,
Stephane

**Comment by tseaver** [comment]
Thanks for the patch.  Merged with https://github.com/repoze/repoze.zodbconn/pull/2.
