### ISSUE TITLE
Parsing multiple zconfig uris

### ISSUE THREAD

**Issue by papachoco** [repoze/repoze.zodbconn#4]
Could we get a new release of repoze.zodbconn with the current code. Sadly, 0.13 does not resolve correctly uris like 

uris = zconfig:///Users/csanchez/tmp/etc/relstorage_conf.xml#users zconfig:///Users/csanchez/tmp/etc/relstorage_conf.xml#users_1

The error is in the class ZConfigURIResolver line 227-229

  (scheme, netloc, path, query, frag) = urlparse.urlsplit(uri)
   # urlparse doesnt understand file URLs and stuffs everything into path
   (scheme, netloc, path, query, frag) = urlparse.urlsplit('http:' + path)

The error is indeed fixed in current checked-in version

Thanks,

Carlos

**Comment by tseaver** [comment]
Released: https://pypi.python.org/pypi/repoze.zodbconn/0.15
